# DISCLAIMER: These parameters have not been optimized
train_steps: 1301
train_batch_size: 98304
eval_batch_size: 1024
iterations_per_loop: 1301
skip_host_call: True
num_cores: 1024
enable_lars: True
label_smoothing: 0.1
